name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Upgrade pip and dependencies
      run: |
        pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install -r ./fastapi/requirements.txt
        pip install -r ./streamlit/requirements.txt

    - name: Check for dependency conflicts
      run: |
        pip check

    - name: Show installed packages
      run: |
        pip list

    - name: Run tests
      run: |
        cd fastapi
        pytest
        cd ../streamlit
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    - name: Deploy
      run: |
        ssh user@your-server "cd /path/to/project && docker-compose pull && docker-compose up -d"
